### ISSUE TITLE
Theme changing not working in Asp.net

### ISSUE THREAD

**Issue by kishoregorle** [usmanhalalit/charisma#44]
hi,

when i'm using charishma template in Asp.net  theme change is not working.

<link id="bs-css"      not working.   is there any way to solve this problem

cheers

**Comment by mesutaydin** [comment]
Hi Usman,

I solved the problem.
charisma.js open; function switchTheme changes;

    function switchTheme(themeName) {
        if (themeName == 'classic') {
            $('#bs-css').attr('href', 'bower_components/bootstrap/dist/css/bootstrap.min.css');
        } else {
           // $('#bs-css').attr('href', 'css/bootstrap-' + themeName + '.min.css');
            
            var link = $("link[rel=stylesheet]")[0].href ;
            var css = link.substring(link.lastIndexOf('/') + 1, link.length)
            css = "css/" + css;
            $('link[href="' + css + '"]').attr('href', 'css/bootstrap-' + themeName + '.min.css');
        }
thanks & regards
