### ISSUE TITLE
Responsive Table Table Tool

### ISSUE THREAD

**Issue by LauLau1991** [usmanhalalit/charisma#72]
Hello, I tried to add table tool, but unable.. Only i can do that if i use the example in datatables, but need to remove your table. Anyway to solve it?

**Comment by usmanhalalit** [comment]
Sorry, I am not sure what you mean, can you please clarify?

**Comment by LauLau1991** [comment]
Sorry for my language. Your responsive table, is designed as the 'Datatable' Design. So i follow the page example try to implement the 'tabletools'
http://datatables.net/extensions/tabletools/

but cannot use, only can do that if remove your table and using own table. Anyway to solve it?
