### ISSUE TITLE
nav ajax on

### ISSUE THREAD

**Issue by gregtampa** [usmanhalalit/charisma#75]
I know the code is here:
https://github.com/usmanhalalit/charisma/blob/master/js/charisma.js#L55
but what exactly would I change to make the nav use ajax permanently.

**Comment by usmanhalalit** [comment]
Replace this line:
https://github.com/usmanhalalit/charisma/blob/master/js/charisma.js#L102
with:
```js
if (e.which != 1 || $(this).parent().hasClass('active')) return;
```
