### ISSUE TITLE
Absolute path linked to "bs-css"

### ISSUE THREAD

**Issue by judgej** [usmanhalalit/charisma#79]
This had me scratching my head a bit.

I have this theme installed in a folder called `charisma`. My framework templates all have `charisma` at the start of the path for all the assets - images, JS, CSS etc. It includes this one specific CSS file:

~~~html
<link href="charisma/css/bootstrap-cerulean.min.css" rel="stylesheet" id="bs-css">
~~~

Every time the page is loaded, it fails to format correctly, as the browser fails to find that script at this location:

> http://mydomian.co.uk/css/bootstrap-cerulean.min.css

So where has `charisma` gone from the path? A bit of a mystery. If I remove the "bs-css" id from the link above, it works. Put the id back in, and page looks for this script in the wrong place again.

"Cerulean" is the default theme, and whatever script is setting the theme, sets the href attribute of the `#bs-css` link element, BUT uses an absolute path. Everything else in the entire admin theme uses relative paths - there are no assumptions that this package is installed on the root path of the domain.

**Comment by judgej** [comment]
This is what the head looks like after the page is loaded. Note the path in the link marked \*\*\*\*\*\*\*\*\*\*\*\*\* has had its "charisma/" prefix stripped by the theme-switching JavaScript.

~~~html
<head>
<meta charset="utf-8">
<title>Free HTML5 Bootstrap Admin Template</title>
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta content="Charisma, a fully featured, responsive, HTML5, Bootstrap admin template." name="description">
<meta content="Muhammad Usman" name="author">
<link id="bs-css" rel="stylesheet" href="css/bootstrap-spacelab.min.css"> *************
<link rel="stylesheet" href="charisma/css/charisma-app.css">
<link rel="stylesheet" href="charisma/bower_components/fullcalendar/dist/fullcalendar.css">
<link media="print" rel="stylesheet" href="charisma/bower_components/fullcalendar/dist/fullcalendar.print.css">
<link rel="stylesheet" href="charisma/bower_components/chosen/chosen.min.css">
<link rel="stylesheet" href="charisma/bower_components/colorbox/example3/colorbox.css">
<link rel="stylesheet" href="charisma/bower_components/responsive-tables/responsive-tables.css">
<link rel="stylesheet" href="charisma/bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css">
<link rel="stylesheet" href="charisma/css/jquery.noty.css">
<link rel="stylesheet" href="charisma/css/noty_theme_default.css">
<link rel="stylesheet" href="charisma/css/elfinder.min.css">
<link rel="stylesheet" href="charisma/css/elfinder.theme.css">
<link rel="stylesheet" href="charisma/css/jquery.iphone.toggle.css">
<link rel="stylesheet" href="charisma/css/uploadify.css">
<link rel="stylesheet" href="charisma/css/animate.min.css">
<script src="charisma/bower_components/jquery/jquery.min.js">
<link href="charisma/img/favicon.ico" rel="shortcut icon">
<script>
</head>
~~~

**Comment by judgej** [comment]
The problem is here: https://github.com/usmanhalalit/charisma/blob/master/js/charisma.js#L45

**Comment by judgej** [comment]
This fixes it for me:

~~~javascript
    function switchTheme(themeName) {
        var scripts= document.getElementsByTagName('script');
        // remove any ?query
        var path= scripts[scripts.length-1].src.split('?')[0];
        // remove last filename part of path
        var mydir= path.split('/').slice(0, -1).join('/')+'/';

        if (themeName == 'classic') {
            $('#bs-css').attr('href', mydir + '../bower_components/bootstrap/dist/css/bootstrap.min.css');
        } else {
            $('#bs-css').attr('href', mydir + '../css/bootstrap-' + themeName + '.min.css');
        }

        $('#themes i').removeClass('glyphicon glyphicon-ok whitespace').addClass('whitespace');
        $('#themes a[data-value=' + themeName + ']').find('i').removeClass('whitespace').addClass('glyphicon glyphicon-ok');
    }
~~~

This creates an absolute link with some additional traversal, so don't consider this the final solution - it was just some copy-paste from SO on my part, that gets me past this problem. So the path now looks like this:

~~~html
<link id="bs-css" rel="stylesheet" href="http://mydomain.com/charisma/js/..css/bootstrap-spacelab.min.css">
~~~

Not ideal, but it demonstrates a fix can be made to make the whole theme totally portable across paths.

**Comment by usmanhalalit** [comment]
Theme switching is for demo purpose. Use your own path if you need theme switching feature on production :)
