### ISSUE TITLE
How to using text area WYSIWYG

### ISSUE THREAD

**Issue by attaporn** [usmanhalalit/charisma#84]
How to using text area WYSIWYG because old version I can used class 

> "cleditor"

 sample below

> <div class="control-group">
> 							  <label class="control-label" for="textarea2">Textarea WYSIWYG</label>
> 							  <div class="controls">
> 								<textarea class="cleditor" id="textarea2" rows="3"></textarea>
> 							  </div>
> 							</div>

**Comment by usmanhalalit** [comment]
New version does not have WYSIWYG editor built in.
